version: '3.8'
services:
  dtaleapp:
    container_name: dtaleapp
    restart: always
    env_file: .env
    build: .
    ports:
      - '5000:5000'
    networks:
      - db_network
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 